version: 2

sources:
  - name: snowflake_sample_data
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
    tables:
      - name: CUSTOMER
      - name: STORE_RETURNS
      - name: DATE_DIM
      - name: CUSTOMER_ADDRESS
      - name: STORE
      - name: CATALOG_SALES
      - name: STORE_SALES
      - name: ITEM